export const pausedOverlayWrapperSelector =
  '[data-testid="paused-overlay-wrapper"]';
export const loadingOverlayWrapperSelector =
  '[data-testid="loading-overlay-wrapper"]';
export const hoverOverlayWrapperSelector =
  '[data-testid="hover-overlay-wrapper"]';
export const playerContainerSelector =
  '[data-testid="hover-video-player-container"]';
export const videoElementSelector = `${playerContainerSelector} video`;
