language: node_js

node_js:
  - 12

cache:
  directories:
    - ~/.npm

notifications:
  email: false

before_install:
  - npm install -g codecov
  - npm install -g @commitlint/travis-cli

script:
  - commitlint-travis
  - npm test
  - codecov
  # Run tests against a built release-ready version of the component
  - npm run test:release

jobs:
  include:
    # Define release stage which handles publishing to npm
    - stage: release
      # Publish to npm on pushes to `main` branch
      if: branch = main AND type = push
      node_js: lts/*
      script: npm run build
      deploy:
        - provider: script
          skip_cleanup: true
          script: npx semantic-release
          on:
            all_branches: true
