language: node_js

node_js:
  - lts/*
  - 10
  - 8

cache:
  directories:
    - ~/.npm

notifications:
  email: false

before_install:
  - npm install -g codecov

script:
  - npm test
  - codecov

jobs:
  include:
    # Define release stage which handles publishing to github page and npm
    - stage: release
      # Only run deploy on pushes to master branch
      if: branch = master AND type = push
      node_js: lts/*
      script: npm run build
      deploy:
        - provider: pages
          local_dir: demo/dist
          fqdn: react-hover-video-player.dev
          project_name: react-hover-video-player
          keep_history: true
          allow_empty_commit: true
          edge:
            branch: master
        - provider: script
          script: npx semantic-release
          edge:
            branch: master
