sudo: false

language: node_js

cache:
  directories:
    - ~/.npm

notifications:
  email: false

node_js:
  - 10

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - npm run build
  - npm run travis-deploy-once "npm run semantic-release"

branches:
  only:
    - master
